### ISSUE TITLE
No such file or directory compiler_problem_torch.py

### ISSUE THREAD

**Issue by Mirocos** [yyuting/Adelta#1]
Hi, sorry to bother you,  I am trying to use Adelta with the following command in readme:
`python run_shader.py render_test_finite_diff_rectangle_2step.py --dir rectangle_2step/ --backend torch --mode visualize_gradient`

And I got an error say such a file is not exists:
`FileNotFoundError: [Errno 2] No such file or directory: '/home/zeming/study/code/Adelta/rectangle_2step/compiler_problem_torch.py'`

I actually did not find any way to generate it and nothing found in source code repository, but how to solve it?

**Comment by yyuting** [comment]
Hi, @Mirocos ,
Thanks for you interest in our project! It is most likely there're some dependency issues in the subprocesses, but the error messages don't propagate to the main thread. Can you try the following two commands and see if the error messages there are more helpful? These commands should be automatically generated by the framework and are printed out after running `python run_shader.py ...`. They will then be executed by a os.system() call, so their error messages might be suppressed.

under the Adelta directory, run:
`python approx_gradient.py --shader test_finite_diff_rectangle_2step --init_values_pool apps/example_init_values/test_finite_diff_rectangle_init_values.npy --metrics 1_scale_L2 --is_col --camera_size 960,640 --render_size 320,320 --tile_offset 390,100 --backend torch --dir &lt;dir&gt; --modes visualize_gradient --gradient_methods_optimization ours --learning_rate 0.01 --finite_diff_both_sides --no_reset_sigma --no_reset_opt`

If the error message for above command is still not helpful, under the Adelta/apps directory, run:
`python render_single.py &lt;dir&gt; render_test_finite_diff_rectangle_2step --backend torch --compiler_modes fw,fw,bw,FD_base_only --use_select_rule 1 --use_multiplication_rule 1 --ndims 2`

**Comment by Mirocos** [comment]
Hi, @yyuting.
Thanks for giving these two ways for solving problem.
With second command I succeed to generate `compiler_problem_torch.py` and then executed the first command could make sense. And there is no error message, so something weird for this opened issue.

Actually I still have one more question:
1. Does `compiler_problem_torch.py` is the output of shading funtion which processed by A_delta with the input original shader program,like glsl format?  But what I found in `A_delta/apps/ ` only some files like `*compiler_problem.frag`

**Comment by yyuting** [comment]
hi @Mirocos ,

After generating `compiler_problem_torch.py` using the above `python render_single.py ...` command, are you able to execute the original `python run_shader.py ...` command without error? 

Regarding your question, the compiler_problem_torch.py (or compiler_problem.py for TF backend, compiler_problem.cpp for Halide backend), are compiler-generated forward+backward program from the input shader program written in our DSL. In this example, the DSL shader is apps/render_test_finite_diff_rectangle_2step.py. 

The Adelta framework can also write the forward pass to GLSL backend that allows interactive animation at interfaces such as shadertoy.com. The apps/*compiler_problem.frag files are examples of GLSL output programs. If you're interested, the Medium tutorials and Youtube video below further demonstrate how to use the GLSL backend.

[Medium Tutorial: Animating the SIGGRAPH logo](https://medium.com/@yutingyang.wh/adelta-tutorial-part-3-animating-the-siggraph-logo-3cbedde5e5e6)
[Medium Tutorial: Animating the Celtic Knot](https://medium.com/@yutingyang.wh/adelta-tutorial-part-4-animating-the-celtic-knot-6935a0d6e535)
[Youtube Live Coding Demo](https://www.youtube.com/watch?v=HvslNmNF4Ss&ab_channel=YutingYang)

**Comment by Mirocos** [comment]
Hi, @yyuting 
Yes, after generating `compiler_problem_torch.py` using the above `python render_single.py` command, I am able to execute the original `python run_shader.py ...` command without error. One more thing I need to configure is that the `--dir <dir>` should be the relative path of `A_delta`, not the `A_delta/apps` though I am in `A_delta/apps`.

And thanks for the detailed document and live demo, I really appreciate it.

**Comment by Mirocos** [comment]
Hi, @yyuting .
I finally found why the original command `python run_shader.py ...` failed with mentioned error message.

It seems the `<dir>` input to `run_shader.py` did not have the same relative path(for main thread and subprocess).
For example, suppose my input `<dir>` is `test_rect` and now I am in the directory `A_delta/apps`. The original command actually generate the `compiler_problem_torch.py`  in `A_delta/apps/test_rect` correctly. But the main thread(I guess) search the `compiler_problem_torch.py` in `A_delta/test_rect`. By using absolute path, everything works well then.
